version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - REACT_APP_API_URL=http://localhost:7001
    depends_on:
      - backend
    networks:
      - erp-network

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "7001:7001"
    environment:
      - PORT=7001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/erp_freitex?schema=public
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
      - redis
    networks:
      - erp-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "7002:5432"
    environment:
      - POSTGRES_DB=erp_freitex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - erp-network

  redis:
    image: redis:7-alpine
    ports:
      - "7003:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp-network

  adminer:
    image: adminer:latest
    ports:
      - "7004:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - erp-network

volumes:
  postgres_data:
  redis_data:

networks:
  erp-network:
    driver: bridge
