-- AlterTable
ALTER TABLE "public"."customers" ADD COLUMN     "allowCreditPurchases" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "creditAvailable" DECIMAL(10,2),
ADD COLUMN     "creditLimit" DECIMAL(10,2),
ADD COLUMN     "creditStatus" TEXT DEFAULT 'ACTIVE',
ADD COLUMN     "creditUsed" DECIMAL(10,2),
ADD COLUMN     "customerSegment" TEXT DEFAULT 'C',
ADD COLUMN     "customerType" TEXT DEFAULT 'REGULAR',
ADD COLUMN     "discountPercentage" DECIMAL(5,2),
ADD COLUMN     "loyaltyPoints" INTEGER DEFAULT 0,
ADD COLUMN     "maxInstallments" INTEGER DEFAULT 12,
ADD COLUMN     "maxPurchaseAmount" DECIMAL(10,2),
ADD COLUMN     "minPurchaseAmount" DECIMAL(10,2),
ADD COLUMN     "occupation" TEXT,
ADD COLUMN     "paymentTerms" TEXT,
ADD COLUMN     "preferredPaymentMethod" TEXT,
ADD COLUMN     "referenceName" TEXT,
ADD COLUMN     "referencePhone" TEXT,
ADD COLUMN     "referenceRelationship" TEXT;
